### ISSUE TITLE
Incorrect Voting Machine Pin Popup

### ISSUE THREAD

**Issue by cjziegle** [mpk2/VoteBoxUI#10]
When a voter does not enter their 5-digit voting machine pin correctly, the following text should appear in the popup: "You must correctly enter your 5-digit voting machine pin to access your ballot. Please try again."

**Comment by mpk2** [comment]
I updated the html and css. I broke it up into two segments because it looked somewhat dense. 

How is this? (updated because I swapped two words around)

![image](https://cloud.githubusercontent.com/assets/7244717/9633738/04be70f4-5154-11e5-8fac-050e4a97acfb.png)

**Comment by cjziegle** [comment]
Perfect, but, can the button say, “OK” instead of,  “Okay."

**Comment by mpk2** [comment]
Absolutely, will make that change and commit it to the repo.

**Comment by cjziegle** [comment]
Thank you!
