### ISSUE TITLE
Review Screen Text

### ISSUE THREAD

**Issue by cjziegle** [mpk2/VoteBoxUI#11]
Can the text, "Review what you're voting for" and the instructions underneath it be made larger? Please make sure that the title is larger than the instructions so that there is a clear hierarchy of information.

**Comment by mpk2** [comment]
Here is my currently updated version (let me know if you'd like things larger still)

![image](https://cloud.githubusercontent.com/assets/7244717/9634157/02f9b04c-5156-11e5-9915-1498401b91cd.png)

**Comment by cjziegle** [comment]
It looks great! Is the text about the same size as the other text used for race titles, the final screens etc.? I just want to make sure it is not larger on just this one page. Hopefully that makes sense.

**Comment by mpk2** [comment]
I had the font size set to 36px, but the race/prop titles were set to (an odd) 34.5px, so I changed it to match. It looks virtually the same, just a tiny bit smaller, but now it matches for sure.

**Comment by cjziegle** [comment]
Even something close is fine.
