### ISSUE TITLE
"Are you finished?" screen text

### ISSUE THREAD

**Issue by cjziegle** [mpk2/VoteBoxUI#12]
On the second-to-last screen, "Are you finished?", the second paragraph's text should be changed to the following: "If you are ready to print your ballot, touch the <bold>Print your ballot</bold> button.

**Comment by mpk2** [comment]
Do you want me to keep the original formatting (e.g. bolded "Print your ballot" in the text)?

**Comment by mpk2** [comment]
This is currently what I've changed it to, assuming your answer to the last question is yes

![image](https://cloud.githubusercontent.com/assets/7244717/9634628/3edd69e4-5158-11e5-9da9-59b1bdf3645e.png)

**Comment by cjziegle** [comment]
Yes.

**Comment by cjziegle** [comment]
Perfect!
