### ISSUE TITLE
PsycTestable should have an options screen and vote-flipping functionality

### ISSUE THREAD

**Issue by mpk2** [mpk2/VoteBoxUI#8]
Specific functionality (and what should be on the options page) is as-of-yet unspecified, but Claudia will be providing it by next week, I expect.

**Comment by mpk2** [comment]
## Wireframes

![imag0636](https://cloud.githubusercontent.com/assets/7244717/9909215/d7554cdc-5c5c-11e5-8e18-0cd72545c0e9.jpg)
![imag0635](https://cloud.githubusercontent.com/assets/7244717/9909216/d76b62f6-5c5c-11e5-85cb-d967e1caa606.jpg)

## Claudia's email about specs

_Location of Changes:_ 
- top of ballot (first 14 races)
- bottom of ballot (last 13 races)
- top of printed ballot (like top band/area of review screen)
- bottom of printed ballot (like bottom band/area of review screen)
- top left quadrant
- top right quadrant
- bottom right quadrant
- bottom left quadrant

_Number of Changes:_ 
- 1
- 2
- 8

_Type of Change:_ 
- change selection
- no selection
- combination

**Comment by cjziegle** [comment]
To clarify, the email about specs applies to the printed ballot vote changes.

Claudia

Claudia Ziegler Acemyan, Ph.D.
Postdoctoral Research Fellow

Human Factors Research Lab
Department of Psychology, Sewall Hall 491
Rice University
6100 Main Street, MS-25
Houston, Texas 77005
Office: 713-348-5038
